language: java
jdk:
  - openjdk11

branches:
  only:
    - develop


# 빌드 전에 gradlew의 권한을 추가한다.
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
# gradle을 통하여 의존성을 받게 되면 이를 캐시하여 배포할 때 마다 다시 받지 않도록 설정한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# main 브랜치에 push 되면 수행되는 명령어이다. 
# 프로젝트 내에 권한이 추가된 gradlew를 활용하여 clean, build를 진행한다.
script: "./gradlew clean build"


before_deploy:
  - zip -r s1dmlgus-instar02 * 
  - mkdir -p deploy
  - mv s1dmlgus-instar02.zip deploy/s1dmlgus-instar02.zip
  

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: s1dmlgus-instar03
    region: ap-northest-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    

notifications:
  email:
    recipients:
      - dmlgusgngl@gmail.com








