language: java
jdk:
  - openjdk11

branches:
  only:
    - develop


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


before_deploy:
  - zip -r s1dmlgus-instar02 * 
  - mkdir -p deploy
  - mv s1dmlgus-instar02.zip deploy/s1dmlgus-instar02.zip
  

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: s1dmlgus-instar03
    region: ap-northest-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    

notifications:
  email:
    recipients:
      - dmlgusgngl@gmail.com








