language: java
jdk:
  - openjdk11

branches:
  only:
    - develop


# 빌드 전에 gradlew의 권한을 추가한다.
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
# gradle을 통하여 의존성을 받게 되면 이를 캐시하여 배포할 때 마다 다시 받지 않도록 설정한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# develop 브랜치에 push 되면 수행되는 명령어이다. 
# 프로젝트 내에 권한이 추가된 gradlew를 활용하여 clean, build를 진행한다.
script: "./gradlew clean build"



before_deploy:

  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/s1dmlgus-instar02.zip


# 외부 서비스와 연동할 행위들을 선언한다.
deploy: 
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis settings에 설정된 값
    bucket: s1dmlgus-instar03 # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리로 이동한다. 해당 위치의 파일만 이동시킨다.
    wait-until-deployed: true
    on:
      branch: develop
    

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis settings에 설정된 값
    bucket: s1dmlgus-instar03 # S3 버킷
    key: s1dmlgus-instar02.zip  
    bundle_type: zip
    application: s1dmlgus-instar02
    deployment_group: s1dmlgus-instar02-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: develop



# CI 실행 완료 시 메일로 
notifications:
  email:
    recipients:
      - dmlgusgngl@gmail.com








